# Generated by Django 3.2.5 on 2021-12-12 05:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BlogMainDatabase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('HashNumber', models.IntegerField(blank=True, default=9999, null=True)),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('imageUrl', models.CharField(blank=True, max_length=255, null=True)),
                ('article', models.TextField()),
                ('dateTimeCreated', models.DateTimeField(auto_now_add=True, null=True)),
                ('author', models.CharField(max_length=150)),
                ('visitor', models.IntegerField(default=0)),
                ('acceptByAdmin', models.BooleanField(blank=True, default=False, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='queueArticle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('HashNumber', models.IntegerField(blank=True, default=9999, null=True)),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('imageUrl', models.CharField(blank=True, max_length=255, null=True)),
                ('article', models.TextField()),
                ('dateTimeCreated', models.DateTimeField(auto_now_add=True, null=True)),
                ('author', models.CharField(max_length=150)),
                ('visitor', models.IntegerField(default=0)),
                ('acceptByAdmin', models.BooleanField(blank=True, default=False, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='comments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('comment', models.TextField()),
                ('email', models.CharField(max_length=255)),
                ('articleHash', models.IntegerField(blank=True, default=None, null=True)),
                ('fkArticle', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='DATABASE.blogmaindatabase')),
            ],
        ),
    ]
