# Generated by Django 3.2.5 on 2021-10-19 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BlogMainDatabase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('HashNumber', models.IntegerField()),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('imageHeader', models.CharField(blank=True, max_length=255, null=True)),
                ('article', models.TextField()),
                ('dateCreated', models.DateField(auto_now_add=True)),
                ('author', models.CharField(max_length=150)),
            ],
        ),
    ]
