# Generated by Django 3.2.5 on 2021-10-19 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DATABASE', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogmaindatabase',
            name='HashNumber',
            field=models.IntegerField(blank=True, default=9999, null=True),
        ),
    ]
