# Generated by Django 3.2.5 on 2021-10-27 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DATABASE', '0003_auto_20211027_0237'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogmaindatabase',
            name='visitor',
            field=models.IntegerField(default=0),
        ),
    ]
