# Generated by Django 3.2.5 on 2021-10-27 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DATABASE', '0004_blogmaindatabase_visitor'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogmaindatabase',
            name='acceptByAdmin',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
