# Generated by Django 3.2.5 on 2021-11-08 06:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DATABASE', '0005_blogmaindatabase_acceptbyadmin'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogmaindatabase',
            name='imageHeader',
        ),
    ]
