# Generated by Django 3.2.5 on 2021-11-20 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DATABASE', '0006_remove_blogmaindatabase_imageheader'),
    ]

    operations = [
        migrations.CreateModel(
            name='queueArticle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('HashNumber', models.IntegerField(blank=True, default=9999, null=True)),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('article', models.TextField()),
                ('dateTimeCreated', models.DateTimeField(auto_now_add=True, null=True)),
                ('author', models.CharField(max_length=150)),
                ('visitor', models.IntegerField(default=0)),
                ('acceptByAdmin', models.BooleanField(blank=True, default=False, null=True)),
            ],
        ),
    ]
