# Generated by Django 3.2.5 on 2021-11-23 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DATABASE', '0007_queuearticle'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogmaindatabase',
            name='imageUrl',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='queuearticle',
            name='imageUrl',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
