# Generated by Django 3.2.5 on 2021-12-04 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DATABASE', '0010_alter_comments_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='email',
            field=models.CharField(max_length=255),
        ),
    ]
