# Generated by Django 3.2.5 on 2021-12-04 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DATABASE', '0011_alter_comments_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comments',
            name='article',
        ),
        migrations.AddField(
            model_name='comments',
            name='articleHash',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
    ]
